const content = [
    "YOUR IN-GAME CHARACTERS WITH EXCLUSIVE BENEFITS TO THE GENESIS (ONE OF WHICH ARE $ATHER & $SIPHER TOKENS)",
    "HIGH ENGAGING COMMUNITY WITH DAILY CONTESTS (OVER 40K ON DISCORD & 20K ON TWITTER)",
    "OWNER BENEFITS FOR HOLDERS. EXCLUSIVE CONTENT, AIRDROPS, COLLECTOR PROGRAM, WHITELIST PERKS & MORE",
]

export default content
